# Configure an instance with the tool jenkins.
- name: Configure Jenkins instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - aws
    - tools_jenkins
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
