# Configure an instance with the admin jenkins.
- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - aws
    - jenkins_admin
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
