---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role oauth_client_setup
# 

#
# vars are namespaced with the module name.
#
oauth_client_setup_role_name: oauth_client_setup

oauth_client_setup_oauth2_clients:
    - {
        name: "{{ ecommerce_service_name | default('None') }}",
        url_root: "{{ ECOMMERCE_ECOMMERCE_URL_ROOT }}",
        id: "{{ ECOMMERCE_SOCIAL_AUTH_EDX_OIDC_KEY }}", 
        secret: "{{ ECOMMERCE_SOCIAL_AUTH_EDX_OIDC_SECRET }}" 
      }
    - {
        name: "{{ INSIGHTS_OAUTH2_APP_CLIENT_NAME | default('None') }}",
        url_root: "{{ INSIGHTS_BASE_URL }}",
        id: "{{ INSIGHTS_OAUTH2_KEY }}",
        secret: "{{ INSIGHTS_OAUTH2_SECRET }}" 
      }
    - {
        name: "{{ programs_service_name | default('None') }}",
        url_root: "{{ PROGRAMS_URL_ROOT }}",
        id: "{{ PROGRAMS_SOCIAL_AUTH_EDX_OIDC_KEY }}",
        secret: "{{ PROGRAMS_SOCIAL_AUTH_EDX_OIDC_SECRET }}"
      }
    - {
        name: "{{ credentials_service_name | default('None') }}",
        url_root: "{{ CREDENTIALS_URL_ROOT }}",
        id: "{{ CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_KEY }}",
        secret: "{{ CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_SECRET }}"
      }
    - {
        name: "{{ discovery_service_name | default('None') }}",
        url_root: "{{ DISCOVERY_URL_ROOT }}",
        id: "{{ DISCOVERY_SOCIAL_AUTH_EDX_OIDC_KEY }}",
        secret: "{{ DISCOVERY_SOCIAL_AUTH_EDX_OIDC_SECRET }}"
    }

#
# OS packages
#

oauth_client_setup_debian_pkgs: []

oauth_client_setup_redhat_pkgs: []
